# 100 numpy exercises

#### 1. 使用别名`np`调用`numpy`库(★☆☆)

In [2]:
import numpy as np

#### 2. 显示当前`numpy`库的版本号和配置信息。 (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
Supported SIMD extensions in this Num

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [19]:
rd = np.random.rand(3, 4)
print(rd)
print('%d Bytes = %d * %d' %(rd.size * rd.itemsize, rd.size, rd.itemsize))
print(type(rd[0][0]))

[[0.01025085 0.23664203 0.0571833  0.3357299 ]
 [0.22606024 0.32372644 0.13238538 0.51178774]
 [0.65881012 0.34421002 0.68864673 0.15701287]]
96 Bytes = 12 * 8
<class 'numpy.float64'>


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [22]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
vec = np.empty((10, )); vec[4] = 1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


- 如果使用`np.zeros()`创建更高维的向量，`size`需要嵌套括号。例如：`np.zeros((3,3))`；
- 而创建一个一维向量，并不需要带括号，只需要输入大小；

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [31]:
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [32]:
vec = vec[20:]
print("Before:", vec)
vec = vec[ : : -1]
print("After :", vec)

Before: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
After : [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [35]:
mat = np.arange(0, 9).reshape((3, 3))
print(mat, "\nshape is ", mat.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
shape is  (3, 3)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [36]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 单位矩阵(identity matrix) (★☆☆)

In [38]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [39]:
np.random.rand(3, 3, 3)

array([[[0.98840242, 0.50409908, 0.73966276],
        [0.11881114, 0.04784136, 0.29361601],
        [0.39091913, 0.33882372, 0.4550768 ]],

       [[0.61885311, 0.18871129, 0.99644353],
        [0.35546225, 0.39450888, 0.99891327],
        [0.05647516, 0.63392684, 0.35717106]],

       [[0.46345534, 0.23768691, 0.47667413],
        [0.34374396, 0.33952225, 0.80188493],
        [0.82045812, 0.0965742 , 0.59591658]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
rd = np.random.rand(10, 10)

Max: 0.9963302290279666 Min: 0.011813284059656537


In [49]:
# 1.8 µs ± 15.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
rd.max(); rd.min()

0.011813284059656537

请使用自带的球最大最小值成员函数：`arr.max()`

In [48]:
# 3.48 µs ± 29.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
np.min(rd); np.max(rd)

0.9963302290279666

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [56]:
rd = np.random.rand(30000)

In [57]:
%%timeit
rd.mean()

7.83 µs ± 76.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


同上，请使用自带方法计算均值。

In [58]:
%%timeit
np.mean(rd)

8.56 µs ± 72.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [70]:
%%timeit
# 填充内部的话，会更快
temp = np.ones((5, 5))
temp[1 : -1, 1 : -1] = 0

1.02 µs ± 5.59 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [92]:
arr = np.random.rand(2, 2) * 100
arr = np.pad(           # 为数组加上边界
    arr,                # 数组
    pad_width=2,        # 边框宽度
    mode='constant',    # 模式：'constant'常数|'edge'边缘值|'linear_ramp'边缘递减|
    constant_values=0   #      'maximum'最大值|'minimum'最小值|'mean'均值|'median'中位数
)
print(arr)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.         55.38754924 57.069254    0.          0.        ]
 [ 0.          0.         35.40624924  5.87661967  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [111]:
print("0 * np.nan              = ", 0 * np.nan)
print("np.nan == np.nan        = ", np.nan == np.nan) # True
print("np.inf > np.nan         = ", np.inf > np.nan)
print("np.nan - np.nan         = ", np.nan - np.nan)  # np.nan
print("np.nan in set([np.nan]) = ", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1          = ", 0.3 == 3 * 0.1)   # True

0 * np.nan              =  nan
np.nan == np.nan        =  False
np.inf > np.nan         =  False
np.nan - np.nan         =  nan
np.nan in set([np.nan]) =  True
0.3 == 3 * 0.1          =  False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [95]:
print(
    np.diag( np.arange(1, 5), -1)
    # 0 ： 对角线上
    # 1 ： 对角线上一个
)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [107]:
temp = np.zeros((8, 8))
temp[1::2, 1::2] = 1
temp[::2, ::2] = 1
print(temp)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [109]:
print( np.unravel_index(99, (6, 7, 8)) )

(1, 5, 3)


将高维数组拉伸成一维数组后的索引。比如：
- 3×3矩阵最中间的那个元素的索引可以用（1,1）表示;
- 也可以在拉伸成一维数组后用一个数字`4 (= 1 × 3 + 1)`表示;

Example: 对于一个 `(6, 7, 8)` 的数组，它的第`99`个元素的索引是 `(1, 5, 3)`.

#### 21. Create a checkerboard 8x8 matrix using the `tile` function (★☆☆)

In [126]:
print( 
    np.tile(
        np.array([[0, 1], [1, 0]]),
        (4, 4)
    )
)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)
$$
Std\,=\,\frac{A-mean(A)}{std(A)}
$$

In [134]:
rd = np.random.rand(5, 5)
rd = (rd - rd.mean()) / rd.std()
rd

array([[ 0.19879968,  0.6012715 ,  0.39660073,  0.13553774, -0.67656764],
       [-0.18546017,  1.34900794, -1.33090996,  0.21941732,  0.03054536],
       [ 1.12309303,  1.58552134,  1.29120959,  1.30238805,  0.07447372],
       [-0.64315275,  1.27078544, -1.18682844,  0.16100333,  0.5564186 ],
       [-1.81213573, -1.15344072, -1.06073337, -0.3782609 , -1.86858371]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [141]:
%%timeit
np.dot(
    np.ones((50, 30)), 
    np.ones((30, 20))
)

4.29 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [142]:
%%timeit
np.ones((50, 30)) @ np.ones((30, 20))

4.48 µs ± 82.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [143]:
%%timeit
Z = np.arange(11)
Z[ (3 < Z) & (Z <= 8) ] *= -1

2.03 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))   # 9
from numpy import *
print(sum(range(5),-1))   # 10
```
---
- `range(5)`表示$0,1,2,3,4$
- Python的`sum()`，对一系列数值求和，$0+1+2+3+4\,+(-1)=9$
- `numpy.sum(a, axis=None)`，数组求和，第二个参数表示**参与运算的轴**

为了更好地理解numpy.sum()中的axis，用一个二维数组演示如下：

In [156]:
a = np.arange(1, 21).reshape(4,5)
a = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]]
)
print('数组：','\n', a)
print('np.sum(a)，未指定轴 ：', np.sum(a))
print('np.sum(a, 0)，维度 0 ', np.sum(a, 0))
print('np.sum(a, 1)，维度 1 ', np.sum(a, 1))

数组： 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
np.sum(a)，未指定轴 ： 60
np.sum(a, 0)，维度 0  [ 4  8 12 16 20]
np.sum(a, 1)，维度 1  [15 15 15 15]


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
    Z**Z          # 合法。输出结果为，对Z中的每一个元素取乘方。
    2 << Z >> 2   # 合法。输出结果为，对2进行左移运算，移动位数为Z中的每个元素；再对运算结果进行右移运算，移动位数为2。
    Z <- Z        # 合法。输出结果为布尔值，将Z中的每一个元素与其相反数进行比较。
    1j*Z          # 合法。输出结果为，Z中的每一个元素与1j相乘（广播机制）。
    Z / 1 / 1     # 合法。需要注意的是，经过除法运算后，Z中的元素由整数变成了浮点数。
    Z < Z > Z     # 不合法。
```

In [167]:
Z = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("\tPython还支持复数，复数由实数部分和虚数部分构成\n\
        \t- 可以用 a + bj \n\
        \t- 或者 complex(a,b) 表示\n\t复数的实部 a 和虚部 b 都是 浮点型\n1j * Z =", 1j * Z)

	Python还支持复数，复数由实数部分和虚数部分构成
        	- 可以用 a + bj 
        	- 或者 complex(a,b) 表示
	复数的实部 a 和虚部 b 都是 浮点型
1j * Z = [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [171]:
np.array([np.nan]).astype(int).astype(float)

array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)